CREATE TABLE AIRPLANES
(
AIRPLANE_ID INT PRIMARY KEY,
AIRPLANE_MODEL_ID INT,
CONSTRAINT FK_AIRMDL_ID FOREIGN KEY(AIRPLANE_MODEL_ID) REFERENCES AIRPLANE_MODELS(AIRPLANE_MODEL_ID)

);

CREATE SEQUENCE SEQ_AIRP_ID;