CREATE TABLE AIRPORTS
(
AIRPORT_CODE INT PRIMARY KEY,
AIRPORT_NAME VARCHAR(255),
AIRPORT_LOCATION_ID  INT ,

STATUS VARCHAR(255),
CONSTRAINT FK_SID FOREIGN KEY(AIRPORT_LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)

);

CREATE SEQUENCE SEQ_AIR_ID;