ALTER TABLE LOCATIONS ADD  LATITUDE DOUBLE PRECISION;
ALTER TABLE LOCATIONS ADD  LONGITUDE DOUBLE PRECISION;
ALTER TABLE CUSTOMERS ADD  EMAIL VARCHAR(255);
ALTER TABLE CUSTOMERS ADD  PASS VARCHAR(255);
ALTER TABLE CUSTOMERS ADD  TELEPHONE_NUM VARCHAR(255);

ALTER TABLE FLIGHTS_SCHEDULE  ADD CONSTRAINT FK_AIRPL_ID FOREIGN KEY(FLIGHT_PLANE) REFERENCES AIRPLANES(AIRPLANE_ID);