CREATE TABLE FAIR_TYPES
(
FAIR_TYPE_ID INT PRIMARY KEY,
FAIR_TYPE VARCHAR(255),
FAIR_CLASS INT,
CONSTRAINT FK_SEAT_CLASS FOREIGN KEY (FAIR_CLASS)  REFERENCES SEAT_CLASSES(SEAT_CLASS_ID)
);


CREATE SEQUENCE SEQ_FT_ID;