CREATE TABLE FLIGHT_SCHEDULES_SEATS
(
FSS_ID INT PRIMARY KEY,
FLIGHT_SCHEDULE_ID INT,
SEAT_ID INT,
CONSTRAINT FK_FS_IDS FOREIGN KEY(FLIGHT_SCHEDULE_ID) REFERENCES FLIGHTS_SCHEDULE(FLIGHTS_SCHEDULE_ID),
CONSTRAINT FK_ST_IDS FOREIGN KEY(SEAT_ID) REFERENCES SEATS(SEAT_ID)
);

CREATE SEQUENCE SEQ_FSS_ID;