CREATE TABLE FLIGHTS(
FLIGHT_CODE int PRIMARY KEY,
SOURCE_AIRPORT_ID int ,
DESTINATION_AIRPORT_ID int,
DEPART_TIME TIMESTAMP ,
ARRIVAL_TIME TIMESTAMP,
DISTANCE INT,
Constraint fk_src_air FOREIGN KEY(SOURCE_AIRPORT_ID) 
REFERENCES AIRPORTS(AIRPORT_CODE),
Constraint fk_dest_air FOREIGN KEY (DESTINATION_AIRPORT_ID)
REFERENCES AIRPORTS(AIRPORT_CODE)
);

CREATE SEQUENCE SEQ_FLIGHT_CODE;
