CREATE TABLE PAYMENTS
(
PAYMENT_ID INT PRIMARY KEY,
CUSTOMER_ID INT,
METHOD_ID INT,
DISCOUNT_ID INT,
CONSTRAINT FK_CID FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
CONSTRAINT FK_MET_ID FOREIGN KEY(METHOD_ID) REFERENCES PAYMENT_METHODS(PAYMENT_METHOD_ID),
CONSTRAINT FK_DISCID FOREIGN KEY(DISCOUNT_ID) REFERENCES DISCOUNTS(DISCOUNT_ID)
);

CREATE SEQUENCE SEQ_PAY_ID;