CREATE TABLE SEATS
(
SEAT_ID INT PRIMARY KEY,
SEAT_MODEL_ID INT,
SEAT_CLASS_ID INT,
CONSTRAINT FK_STMDL_ID FOREIGN KEY(SEAT_MODEL_ID) REFERENCES AIRPLANE_MODELS(AIRPLANE_MODEL_ID),
CONSTRAINT FK_STCLS_ID FOREIGN KEY(SEAT_CLASS_ID) REFERENCES SEAT_CLASSES(SEAT_CLASS_ID)

);

CREATE SEQUENCE SEQ_SEAT_ID;
