CREATE TABLE TICKETS
(
TICKET_ID INT PRIMARY KEY,
TICKET_STATUS VARCHAR(255),
TICKET_FSS_ID INT,
TICKET_FAIR_TYPE INT,
TICKET_BOOKING_ID INT,
CONSTRAINT FK_TICK_FSS FOREIGN KEY(TICKET_FSS_ID) REFERENCES FLIGHT_SCHEDULES_SEATS(FSS_ID),
CONSTRAINT FK_TICK_FT FOREIGN KEY(TICKET_FAIR_TYPE) REFERENCES FAIR_TYPES(FAIR_TYPE_ID),
CONSTRAINT FK_TICK_BID FOREIGN KEY(TICKET_BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID)


);

CREATE SEQUENCE SEQ_TICK_ID;